version: "3.8"

services:
  backend:
    build: .
    container_name: racademic-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - racademic-data:/app/dev.db
    restart: unless-stopped

volumes:
  racademic-data:
